version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: scraping_python